[tox]
envlist = py310, py311, py313, lint, type, format
skipsdist = true
skip_missing_interpreters = true

[testenv]
skip_install = true
changedir = {toxinidir}
setenv =
    PYTHONPATH = {toxinidir}
allowlist_externals =
    {toxinidir}/.venv/bin/pytest
    {toxinidir}/.venv/bin/black
    {toxinidir}/.venv/bin/isort
    {toxinidir}/.venv/bin/flake8
    {toxinidir}/.venv/bin/mypy
commands =
    {toxinidir}/.venv/bin/pytest

[testenv:lint]
skip_install = true
commands =
    {toxinidir}/.venv/bin/flake8 filegrouper tests main.py

[testenv:type]
skip_install = true
commands =
    {toxinidir}/.venv/bin/mypy filegrouper

[testenv:format]
skip_install = true
commands =
    {toxinidir}/.venv/bin/black --check filegrouper tests main.py
    {toxinidir}/.venv/bin/isort --check-only filegrouper tests main.py
