"""GUI text resources and selection item definitions."""

from __future__ import annotations

from types import MappingProxyType

from .models import DedupeMode, ExecutionScope, OrganizationMode

TR = MappingProxyType(
    {
        "title": "ArchiFlow",
        "subtitle": "Dağınık dosyaları düzenleyin. Gereksiz kopyaları temizleyin.",
        "welcome_title": "Dağınık dosyaları düzenleyin. Gereksiz kopyaları temizleyin.",
        "welcome_subtitle": "ArchiFlow klasörünüzü analiz eder, aynı dosyaları bulur ve güvenle temizlemenizi sağlar.",
        "welcome_category": "Akıllı arşiv düzenleyici",
        "welcome_pick": "Analiz edilecek klasörü seç",
        "welcome_recent": "Son analiz edilen klasörü aç",
        "welcome_advanced": "Gelişmiş ayarlar (isteğe bağlı)",
        "setup_title": "Hangi klasörü analiz etmek istiyorsunuz?",
        "source": "1) Analiz edilecek klasör",
        "target": "2) Düzenlenen dosyaların kaydedileceği klasör",
        "browse": "Gözat…",
        "scope": "3) Analiz türü",
        "workflow": "Çalışma şekli",
        "profile": "Hazır ayar",
        "profile_apply": "Uygula",
        "profile_loaded": "Hazır ayar yüklendi",
        "flow_all": "Tümü (önerilen)",
        "flow_all_desc": "Kopyaları temizler ve dosyaları düzenler.",
        "flow_dedupe": "Sadece kopya temizle",
        "flow_dedupe_desc": "Yalnızca kopya tespiti ve güvenli temizlik yapılır.",
        "flow_group": "Sadece dosya düzenle",
        "flow_group_desc": "Sadece klasörleme ve düzenleme çalışır.",
        "workflow_hint": "3 adım: Klasörü seçin → Analizi başlatın → Sonuçları güvenle uygulayın.",
        "target_not_needed": "Bu çalışma şeklinde hedef klasör gerekli değil.",
        "mode": "Dosya düzenleme şekli",
        "dedupe": "Kopya işlemi",
        "dry_run": "Test modu (hiçbir dosya değiştirilmez)",
        "similar": "Benzer fotoğrafları tespit et (silme işlemi yapılmaz)",
        "similar_unavailable": "Benzer görsel analizi için Pillow gerekir.",
        "advanced_helper": "Gelişmiş ayarlar isteğe bağlıdır (çoğu kullanıcı için gerekli değildir).",
        "filters": "Filtreler…",
        "preview": "Analizi Başlat",
        "preview_safety_note": "Dosyalarınız sadece analiz edilir. Hiçbir şey silinmez.",
        "apply": "Sonuçları Uygula",
        "back": "Geri",
        "rescan": "Tekrar Tara",
        "pick_different": "Farklı Klasör Seç",
        "open_report": "Raporu Aç",
        "new_operation": "Yeni İşlem Başlat",
        "pause": "Duraklat",
        "resume": "Devam",
        "cancel": "İptal",
        "undo": "Geri al",
        "export": "Rapor",
        "analysis_title": "Analiz devam ediyor",
        "results_title": "Analiz Sonuçları",
        "success_title": "İşlem tamamlandı",
        "success_subtitle": "Seçtiğiniz işlemler güvenli şekilde tamamlandı.",
        "processed_files": "İşlenen Dosya",
        "recovered_space": "Kazanılan Alan",
        "tab_dupes": "Kopyalar",
        "tab_logs": "Log",
        "tab_similar": "Benzer Görseller",
        "ready": "Hazır",
        "running": "Çalışıyor…",
        "paused": "Duraklatıldı",
        "cancelled": "İptal edildi",
        "done": "Tamamlandı",
        "err": "Hata",
        "advanced_show": "► Gelişmiş ayarlar (isteğe bağlı)",
        "advanced_hide": "▼ Gelişmiş ayarlar (isteğe bağlı)",
        "need_source": "Kaynak klasör seçmeden başlayamazsın.",
        "need_target_undo": "Geri alma için hedef klasör gerekli.",
        "need_preview": "Önce bir önizleme/uygulama çalıştır.",
        "preview_summary": "Önizleme Özeti",
        "sum_total": "Toplam dosya",
        "sum_dupes": "Bulunan Kopya",
        "sum_dupe_groups": "Kopya Grup Sayısı",
        "sum_reclaim": "Kazanılabilir Alan",
        "sum_quarantine": "Karantinaya Gidecek Dosya",
        "sum_organize": "Düzenlenecek Dosya",
        "sum_errors": "Hata sayısı",
        "sum_skipped": "Atlanan Dosya",
        "confirm_apply_title": "Uygulama Onayı",
        "confirm_apply_text": "Seçilen sonuçlar uygulanacak. Devam etmek istiyor musunuz?",
        "confirm_continue": "Devam Et",
        "confirm_cancel": "Vazgeç",
        "summary_dialog_title": "Çalışma Özeti",
        "summary_preview_done": "Önizleme tamamlandı.",
        "summary_apply_done": "Uygulama tamamlandı.",
        "open_quarantine": "Karantina Klasörünü Aç",
        "quarantine_missing": "Karantina klasörü henüz oluşmadı.",
        "open_file_location_failed": "Dosya konumu açılamadı.",
        "error_details_hint": "Detaylar için Log sekmesini kontrol edin.",
        "dupe_detail": "Grup Detayı",
        "empty_duplicates": "Henüz kopya grubu yok. Analiz tamamlandığında burada listelenecek.",
        "empty_logs": "Bu adımda gösterilecek log yok.",
        "empty_similar": "Benzer görsel sonucu bulunamadı.",
        "results_hint": "Sonuçları uygulamadan önce aşağıdaki özet ve listeleri kontrol edin.",
        "analysis_hint": "Analiz sürerken uygulamayı kapatmadan bekleyin. İsterseniz duraklatabilir veya iptal edebilirsiniz.",
        "trust_item_1": "Hiçbir dosya izinsiz silinmez",
        "trust_item_2": "İşlemler geri alınabilir",
        "trust_item_3": "Önce analiz, sonra uygulama",
        "results_gain_placeholder": "Analiz tamamlandığında kazanım burada gösterilir.",
        "intro_loading": "ArchiFlow başlatılıyor...",
    }
)

SCOPE_ITEMS = (
    ("Grupla + Kopya Temizle", ExecutionScope.GROUP_AND_DEDUPE),
    ("Sadece Grupla", ExecutionScope.GROUP_ONLY),
    ("Sadece Kopya Temizle", ExecutionScope.DEDUPE_ONLY),
)
MODE_ITEMS = (
    ("Kopyala", OrganizationMode.COPY),
    ("Taşı", OrganizationMode.MOVE),
)
DEDUPE_ITEMS = (
    ("Karantina", DedupeMode.QUARANTINE),
    ("Kapalı", DedupeMode.OFF),
    ("Sil (tehlikeli)", DedupeMode.DELETE),
)
WORKFLOW_ITEMS = (
    (TR["flow_all"], ExecutionScope.GROUP_AND_DEDUPE, TR["flow_all_desc"]),
    (TR["flow_dedupe"], ExecutionScope.DEDUPE_ONLY, TR["flow_dedupe_desc"]),
    (TR["flow_group"], ExecutionScope.GROUP_ONLY, TR["flow_group_desc"]),
)
